### ISSUE TITLE
switch to rust

### ISSUE THREAD

**Issue by rohannair** [MichalMalyska/default_python_starter#1]
it's better. duh

**Comment by seanlennaerts** [comment]
@MichalMalyska when can we expect this to be done? My team relies on default_python_starter for critical systems. Our customers are being affected. We would appreciate it if you prioritize this issue and provide us a timeline asap.

**Comment by ShaabanM** [comment]
@MichalMalyska please resolve this issue in a timely manner as it is critical for multiple astronomy experiments.

**Comment by MichalMalyska** [comment]
I love you too guys @rohannair @seanlennaerts @ShaabanM

**Comment by MichalMalyska** [comment]
Solved with #ead96db
